version: 0.2

phases:
  install: 
    commands:
      - npm install --save-dev -g pack-zip
  build:
    commands:
      - echo Build started on `date`
      - cd authentication/create-s3-upload-policy-document
      - pwd
      - npm install
      - npm run build-aws-lambda
      - aws s3 cp get-upload-policy.zip s3://aksh-test-deploy/transcoder/get-upload-policy.zip 
      - aws s3 cp appspec.yml s3://aksh-test-deploy/transcoder/appspec.yml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - authentication/create-s3-upload-policy-document/appspec.yml
  discard-paths: yes
